# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/CMakeFiles /home/student//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named plazza

# Build rule for target.
plazza: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 plazza
.PHONY : plazza

# fast build rule for target.
plazza/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/build
.PHONY : plazza/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named tests_run

# Build rule for target.
tests_run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests_run
.PHONY : tests_run

# fast build rule for target.
tests_run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests_run.dir/build.make CMakeFiles/tests_run.dir/build
.PHONY : tests_run/fast

src/Error/Error.o: src/Error/Error.cpp.o
.PHONY : src/Error/Error.o

# target to build an object file
src/Error/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Error/Error.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Error/Error.cpp.o
.PHONY : src/Error/Error.cpp.o

src/Error/Error.i: src/Error/Error.cpp.i
.PHONY : src/Error/Error.i

# target to preprocess a source file
src/Error/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Error/Error.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Error/Error.cpp.i
.PHONY : src/Error/Error.cpp.i

src/Error/Error.s: src/Error/Error.cpp.s
.PHONY : src/Error/Error.s

# target to generate assembly for a file
src/Error/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Error/Error.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Error/Error.cpp.s
.PHONY : src/Error/Error.cpp.s

src/IConditionVariable/ConditionVariable.o: src/IConditionVariable/ConditionVariable.cpp.o
.PHONY : src/IConditionVariable/ConditionVariable.o

# target to build an object file
src/IConditionVariable/ConditionVariable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IConditionVariable/ConditionVariable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IConditionVariable/ConditionVariable.cpp.o
.PHONY : src/IConditionVariable/ConditionVariable.cpp.o

src/IConditionVariable/ConditionVariable.i: src/IConditionVariable/ConditionVariable.cpp.i
.PHONY : src/IConditionVariable/ConditionVariable.i

# target to preprocess a source file
src/IConditionVariable/ConditionVariable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IConditionVariable/ConditionVariable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IConditionVariable/ConditionVariable.cpp.i
.PHONY : src/IConditionVariable/ConditionVariable.cpp.i

src/IConditionVariable/ConditionVariable.s: src/IConditionVariable/ConditionVariable.cpp.s
.PHONY : src/IConditionVariable/ConditionVariable.s

# target to generate assembly for a file
src/IConditionVariable/ConditionVariable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IConditionVariable/ConditionVariable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IConditionVariable/ConditionVariable.cpp.s
.PHONY : src/IConditionVariable/ConditionVariable.cpp.s

src/IMutex/Mutex.o: src/IMutex/Mutex.cpp.o
.PHONY : src/IMutex/Mutex.o

# target to build an object file
src/IMutex/Mutex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IMutex/Mutex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IMutex/Mutex.cpp.o
.PHONY : src/IMutex/Mutex.cpp.o

src/IMutex/Mutex.i: src/IMutex/Mutex.cpp.i
.PHONY : src/IMutex/Mutex.i

# target to preprocess a source file
src/IMutex/Mutex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IMutex/Mutex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IMutex/Mutex.cpp.i
.PHONY : src/IMutex/Mutex.cpp.i

src/IMutex/Mutex.s: src/IMutex/Mutex.cpp.s
.PHONY : src/IMutex/Mutex.s

# target to generate assembly for a file
src/IMutex/Mutex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IMutex/Mutex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IMutex/Mutex.cpp.s
.PHONY : src/IMutex/Mutex.cpp.s

src/IMutex/ScopedLock/ScopedLock.o: src/IMutex/ScopedLock/ScopedLock.cpp.o
.PHONY : src/IMutex/ScopedLock/ScopedLock.o

# target to build an object file
src/IMutex/ScopedLock/ScopedLock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IMutex/ScopedLock/ScopedLock.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IMutex/ScopedLock/ScopedLock.cpp.o
.PHONY : src/IMutex/ScopedLock/ScopedLock.cpp.o

src/IMutex/ScopedLock/ScopedLock.i: src/IMutex/ScopedLock/ScopedLock.cpp.i
.PHONY : src/IMutex/ScopedLock/ScopedLock.i

# target to preprocess a source file
src/IMutex/ScopedLock/ScopedLock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IMutex/ScopedLock/ScopedLock.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IMutex/ScopedLock/ScopedLock.cpp.i
.PHONY : src/IMutex/ScopedLock/ScopedLock.cpp.i

src/IMutex/ScopedLock/ScopedLock.s: src/IMutex/ScopedLock/ScopedLock.cpp.s
.PHONY : src/IMutex/ScopedLock/ScopedLock.s

# target to generate assembly for a file
src/IMutex/ScopedLock/ScopedLock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/IMutex/ScopedLock/ScopedLock.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/IMutex/ScopedLock/ScopedLock.cpp.s
.PHONY : src/IMutex/ScopedLock/ScopedLock.cpp.s

src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.o: src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.o
.PHONY : src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.o

# target to build an object file
src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.o
.PHONY : src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.o

src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.i: src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.i
.PHONY : src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.i

# target to preprocess a source file
src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.i
.PHONY : src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.i

src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.s: src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.s
.PHONY : src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.s

# target to generate assembly for a file
src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.s
.PHONY : src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.cpp.s

src/Plazza/Kitchen/Cook/CookRoutine.o: src/Plazza/Kitchen/Cook/CookRoutine.cpp.o
.PHONY : src/Plazza/Kitchen/Cook/CookRoutine.o

# target to build an object file
src/Plazza/Kitchen/Cook/CookRoutine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Cook/CookRoutine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Cook/CookRoutine.cpp.o
.PHONY : src/Plazza/Kitchen/Cook/CookRoutine.cpp.o

src/Plazza/Kitchen/Cook/CookRoutine.i: src/Plazza/Kitchen/Cook/CookRoutine.cpp.i
.PHONY : src/Plazza/Kitchen/Cook/CookRoutine.i

# target to preprocess a source file
src/Plazza/Kitchen/Cook/CookRoutine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Cook/CookRoutine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Cook/CookRoutine.cpp.i
.PHONY : src/Plazza/Kitchen/Cook/CookRoutine.cpp.i

src/Plazza/Kitchen/Cook/CookRoutine.s: src/Plazza/Kitchen/Cook/CookRoutine.cpp.s
.PHONY : src/Plazza/Kitchen/Cook/CookRoutine.s

# target to generate assembly for a file
src/Plazza/Kitchen/Cook/CookRoutine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Cook/CookRoutine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Cook/CookRoutine.cpp.s
.PHONY : src/Plazza/Kitchen/Cook/CookRoutine.cpp.s

src/Plazza/Kitchen/Kitchen.o: src/Plazza/Kitchen/Kitchen.cpp.o
.PHONY : src/Plazza/Kitchen/Kitchen.o

# target to build an object file
src/Plazza/Kitchen/Kitchen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Kitchen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Kitchen.cpp.o
.PHONY : src/Plazza/Kitchen/Kitchen.cpp.o

src/Plazza/Kitchen/Kitchen.i: src/Plazza/Kitchen/Kitchen.cpp.i
.PHONY : src/Plazza/Kitchen/Kitchen.i

# target to preprocess a source file
src/Plazza/Kitchen/Kitchen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Kitchen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Kitchen.cpp.i
.PHONY : src/Plazza/Kitchen/Kitchen.cpp.i

src/Plazza/Kitchen/Kitchen.s: src/Plazza/Kitchen/Kitchen.cpp.s
.PHONY : src/Plazza/Kitchen/Kitchen.s

# target to generate assembly for a file
src/Plazza/Kitchen/Kitchen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Kitchen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Kitchen.cpp.s
.PHONY : src/Plazza/Kitchen/Kitchen.cpp.s

src/Plazza/Kitchen/Pantry/Pantry.o: src/Plazza/Kitchen/Pantry/Pantry.cpp.o
.PHONY : src/Plazza/Kitchen/Pantry/Pantry.o

# target to build an object file
src/Plazza/Kitchen/Pantry/Pantry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Pantry/Pantry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Pantry/Pantry.cpp.o
.PHONY : src/Plazza/Kitchen/Pantry/Pantry.cpp.o

src/Plazza/Kitchen/Pantry/Pantry.i: src/Plazza/Kitchen/Pantry/Pantry.cpp.i
.PHONY : src/Plazza/Kitchen/Pantry/Pantry.i

# target to preprocess a source file
src/Plazza/Kitchen/Pantry/Pantry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Pantry/Pantry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Pantry/Pantry.cpp.i
.PHONY : src/Plazza/Kitchen/Pantry/Pantry.cpp.i

src/Plazza/Kitchen/Pantry/Pantry.s: src/Plazza/Kitchen/Pantry/Pantry.cpp.s
.PHONY : src/Plazza/Kitchen/Pantry/Pantry.s

# target to generate assembly for a file
src/Plazza/Kitchen/Pantry/Pantry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Kitchen/Pantry/Pantry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Kitchen/Pantry/Pantry.cpp.s
.PHONY : src/Plazza/Kitchen/Pantry/Pantry.cpp.s

src/Plazza/Parser/Parser.o: src/Plazza/Parser/Parser.cpp.o
.PHONY : src/Plazza/Parser/Parser.o

# target to build an object file
src/Plazza/Parser/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Parser/Parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Parser/Parser.cpp.o
.PHONY : src/Plazza/Parser/Parser.cpp.o

src/Plazza/Parser/Parser.i: src/Plazza/Parser/Parser.cpp.i
.PHONY : src/Plazza/Parser/Parser.i

# target to preprocess a source file
src/Plazza/Parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Parser/Parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Parser/Parser.cpp.i
.PHONY : src/Plazza/Parser/Parser.cpp.i

src/Plazza/Parser/Parser.s: src/Plazza/Parser/Parser.cpp.s
.PHONY : src/Plazza/Parser/Parser.s

# target to generate assembly for a file
src/Plazza/Parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Parser/Parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Parser/Parser.cpp.s
.PHONY : src/Plazza/Parser/Parser.cpp.s

src/Plazza/Pizza/APizza.o: src/Plazza/Pizza/APizza.cpp.o
.PHONY : src/Plazza/Pizza/APizza.o

# target to build an object file
src/Plazza/Pizza/APizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/APizza.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/APizza.cpp.o
.PHONY : src/Plazza/Pizza/APizza.cpp.o

src/Plazza/Pizza/APizza.i: src/Plazza/Pizza/APizza.cpp.i
.PHONY : src/Plazza/Pizza/APizza.i

# target to preprocess a source file
src/Plazza/Pizza/APizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/APizza.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/APizza.cpp.i
.PHONY : src/Plazza/Pizza/APizza.cpp.i

src/Plazza/Pizza/APizza.s: src/Plazza/Pizza/APizza.cpp.s
.PHONY : src/Plazza/Pizza/APizza.s

# target to generate assembly for a file
src/Plazza/Pizza/APizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/APizza.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/APizza.cpp.s
.PHONY : src/Plazza/Pizza/APizza.cpp.s

src/Plazza/Pizza/Americana/AmericanaPizza.o: src/Plazza/Pizza/Americana/AmericanaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Americana/AmericanaPizza.o

# target to build an object file
src/Plazza/Pizza/Americana/AmericanaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Americana/AmericanaPizza.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Americana/AmericanaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Americana/AmericanaPizza.cpp.o

src/Plazza/Pizza/Americana/AmericanaPizza.i: src/Plazza/Pizza/Americana/AmericanaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Americana/AmericanaPizza.i

# target to preprocess a source file
src/Plazza/Pizza/Americana/AmericanaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Americana/AmericanaPizza.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Americana/AmericanaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Americana/AmericanaPizza.cpp.i

src/Plazza/Pizza/Americana/AmericanaPizza.s: src/Plazza/Pizza/Americana/AmericanaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Americana/AmericanaPizza.s

# target to generate assembly for a file
src/Plazza/Pizza/Americana/AmericanaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Americana/AmericanaPizza.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Americana/AmericanaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Americana/AmericanaPizza.cpp.s

src/Plazza/Pizza/Fantasia/FantasiaPizza.o: src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Fantasia/FantasiaPizza.o

# target to build an object file
src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.o

src/Plazza/Pizza/Fantasia/FantasiaPizza.i: src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Fantasia/FantasiaPizza.i

# target to preprocess a source file
src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.i

src/Plazza/Pizza/Fantasia/FantasiaPizza.s: src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Fantasia/FantasiaPizza.s

# target to generate assembly for a file
src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Fantasia/FantasiaPizza.cpp.s

src/Plazza/Pizza/Margarita/MargaritaPizza.o: src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Margarita/MargaritaPizza.o

# target to build an object file
src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.o

src/Plazza/Pizza/Margarita/MargaritaPizza.i: src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Margarita/MargaritaPizza.i

# target to preprocess a source file
src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.i

src/Plazza/Pizza/Margarita/MargaritaPizza.s: src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Margarita/MargaritaPizza.s

# target to generate assembly for a file
src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Margarita/MargaritaPizza.cpp.s

src/Plazza/Pizza/Regina/ReginaPizza.o: src/Plazza/Pizza/Regina/ReginaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Regina/ReginaPizza.o

# target to build an object file
src/Plazza/Pizza/Regina/ReginaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Regina/ReginaPizza.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Regina/ReginaPizza.cpp.o
.PHONY : src/Plazza/Pizza/Regina/ReginaPizza.cpp.o

src/Plazza/Pizza/Regina/ReginaPizza.i: src/Plazza/Pizza/Regina/ReginaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Regina/ReginaPizza.i

# target to preprocess a source file
src/Plazza/Pizza/Regina/ReginaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Regina/ReginaPizza.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Regina/ReginaPizza.cpp.i
.PHONY : src/Plazza/Pizza/Regina/ReginaPizza.cpp.i

src/Plazza/Pizza/Regina/ReginaPizza.s: src/Plazza/Pizza/Regina/ReginaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Regina/ReginaPizza.s

# target to generate assembly for a file
src/Plazza/Pizza/Regina/ReginaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Pizza/Regina/ReginaPizza.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Pizza/Regina/ReginaPizza.cpp.s
.PHONY : src/Plazza/Pizza/Regina/ReginaPizza.cpp.s

src/Plazza/Reception/Reception.o: src/Plazza/Reception/Reception.cpp.o
.PHONY : src/Plazza/Reception/Reception.o

# target to build an object file
src/Plazza/Reception/Reception.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Reception/Reception.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Reception/Reception.cpp.o
.PHONY : src/Plazza/Reception/Reception.cpp.o

src/Plazza/Reception/Reception.i: src/Plazza/Reception/Reception.cpp.i
.PHONY : src/Plazza/Reception/Reception.i

# target to preprocess a source file
src/Plazza/Reception/Reception.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Reception/Reception.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Reception/Reception.cpp.i
.PHONY : src/Plazza/Reception/Reception.cpp.i

src/Plazza/Reception/Reception.s: src/Plazza/Reception/Reception.cpp.s
.PHONY : src/Plazza/Reception/Reception.s

# target to generate assembly for a file
src/Plazza/Reception/Reception.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Plazza/Reception/Reception.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Plazza/Reception/Reception.cpp.s
.PHONY : src/Plazza/Reception/Reception.cpp.s

src/Timer/Timer.o: src/Timer/Timer.cpp.o
.PHONY : src/Timer/Timer.o

# target to build an object file
src/Timer/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Timer/Timer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Timer/Timer.cpp.o
.PHONY : src/Timer/Timer.cpp.o

src/Timer/Timer.i: src/Timer/Timer.cpp.i
.PHONY : src/Timer/Timer.i

# target to preprocess a source file
src/Timer/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Timer/Timer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Timer/Timer.cpp.i
.PHONY : src/Timer/Timer.cpp.i

src/Timer/Timer.s: src/Timer/Timer.cpp.s
.PHONY : src/Timer/Timer.s

# target to generate assembly for a file
src/Timer/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/Timer/Timer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/src/Timer/Timer.cpp.s
.PHONY : src/Timer/Timer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/plazza.dir/build.make CMakeFiles/plazza.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/KitchenClass/Kitchen.o: tests/KitchenClass/Kitchen.cpp.o
.PHONY : tests/KitchenClass/Kitchen.o

# target to build an object file
tests/KitchenClass/Kitchen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/KitchenClass/Kitchen.cpp.o
.PHONY : tests/KitchenClass/Kitchen.cpp.o

tests/KitchenClass/Kitchen.i: tests/KitchenClass/Kitchen.cpp.i
.PHONY : tests/KitchenClass/Kitchen.i

# target to preprocess a source file
tests/KitchenClass/Kitchen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/KitchenClass/Kitchen.cpp.i
.PHONY : tests/KitchenClass/Kitchen.cpp.i

tests/KitchenClass/Kitchen.s: tests/KitchenClass/Kitchen.cpp.s
.PHONY : tests/KitchenClass/Kitchen.s

# target to generate assembly for a file
tests/KitchenClass/Kitchen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/KitchenClass/Kitchen.cpp.s
.PHONY : tests/KitchenClass/Kitchen.cpp.s

tests/KitchenClass/PantryClass/Pantry.o: tests/KitchenClass/PantryClass/Pantry.cpp.o
.PHONY : tests/KitchenClass/PantryClass/Pantry.o

# target to build an object file
tests/KitchenClass/PantryClass/Pantry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/KitchenClass/PantryClass/Pantry.cpp.o
.PHONY : tests/KitchenClass/PantryClass/Pantry.cpp.o

tests/KitchenClass/PantryClass/Pantry.i: tests/KitchenClass/PantryClass/Pantry.cpp.i
.PHONY : tests/KitchenClass/PantryClass/Pantry.i

# target to preprocess a source file
tests/KitchenClass/PantryClass/Pantry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/KitchenClass/PantryClass/Pantry.cpp.i
.PHONY : tests/KitchenClass/PantryClass/Pantry.cpp.i

tests/KitchenClass/PantryClass/Pantry.s: tests/KitchenClass/PantryClass/Pantry.cpp.s
.PHONY : tests/KitchenClass/PantryClass/Pantry.s

# target to generate assembly for a file
tests/KitchenClass/PantryClass/Pantry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/KitchenClass/PantryClass/Pantry.cpp.s
.PHONY : tests/KitchenClass/PantryClass/Pantry.cpp.s

tests/ParserClass.o: tests/ParserClass.cpp.o
.PHONY : tests/ParserClass.o

# target to build an object file
tests/ParserClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/ParserClass.cpp.o
.PHONY : tests/ParserClass.cpp.o

tests/ParserClass.i: tests/ParserClass.cpp.i
.PHONY : tests/ParserClass.i

# target to preprocess a source file
tests/ParserClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/ParserClass.cpp.i
.PHONY : tests/ParserClass.cpp.i

tests/ParserClass.s: tests/ParserClass.cpp.s
.PHONY : tests/ParserClass.s

# target to generate assembly for a file
tests/ParserClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/ParserClass.cpp.s
.PHONY : tests/ParserClass.cpp.s

tests/PizzaClass/AmericanaPizza.o: tests/PizzaClass/AmericanaPizza.cpp.o
.PHONY : tests/PizzaClass/AmericanaPizza.o

# target to build an object file
tests/PizzaClass/AmericanaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/AmericanaPizza.cpp.o
.PHONY : tests/PizzaClass/AmericanaPizza.cpp.o

tests/PizzaClass/AmericanaPizza.i: tests/PizzaClass/AmericanaPizza.cpp.i
.PHONY : tests/PizzaClass/AmericanaPizza.i

# target to preprocess a source file
tests/PizzaClass/AmericanaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/AmericanaPizza.cpp.i
.PHONY : tests/PizzaClass/AmericanaPizza.cpp.i

tests/PizzaClass/AmericanaPizza.s: tests/PizzaClass/AmericanaPizza.cpp.s
.PHONY : tests/PizzaClass/AmericanaPizza.s

# target to generate assembly for a file
tests/PizzaClass/AmericanaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/AmericanaPizza.cpp.s
.PHONY : tests/PizzaClass/AmericanaPizza.cpp.s

tests/PizzaClass/FantasiaPizza.o: tests/PizzaClass/FantasiaPizza.cpp.o
.PHONY : tests/PizzaClass/FantasiaPizza.o

# target to build an object file
tests/PizzaClass/FantasiaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/FantasiaPizza.cpp.o
.PHONY : tests/PizzaClass/FantasiaPizza.cpp.o

tests/PizzaClass/FantasiaPizza.i: tests/PizzaClass/FantasiaPizza.cpp.i
.PHONY : tests/PizzaClass/FantasiaPizza.i

# target to preprocess a source file
tests/PizzaClass/FantasiaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/FantasiaPizza.cpp.i
.PHONY : tests/PizzaClass/FantasiaPizza.cpp.i

tests/PizzaClass/FantasiaPizza.s: tests/PizzaClass/FantasiaPizza.cpp.s
.PHONY : tests/PizzaClass/FantasiaPizza.s

# target to generate assembly for a file
tests/PizzaClass/FantasiaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/FantasiaPizza.cpp.s
.PHONY : tests/PizzaClass/FantasiaPizza.cpp.s

tests/PizzaClass/MargaritaPizza.o: tests/PizzaClass/MargaritaPizza.cpp.o
.PHONY : tests/PizzaClass/MargaritaPizza.o

# target to build an object file
tests/PizzaClass/MargaritaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/MargaritaPizza.cpp.o
.PHONY : tests/PizzaClass/MargaritaPizza.cpp.o

tests/PizzaClass/MargaritaPizza.i: tests/PizzaClass/MargaritaPizza.cpp.i
.PHONY : tests/PizzaClass/MargaritaPizza.i

# target to preprocess a source file
tests/PizzaClass/MargaritaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/MargaritaPizza.cpp.i
.PHONY : tests/PizzaClass/MargaritaPizza.cpp.i

tests/PizzaClass/MargaritaPizza.s: tests/PizzaClass/MargaritaPizza.cpp.s
.PHONY : tests/PizzaClass/MargaritaPizza.s

# target to generate assembly for a file
tests/PizzaClass/MargaritaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/MargaritaPizza.cpp.s
.PHONY : tests/PizzaClass/MargaritaPizza.cpp.s

tests/PizzaClass/ReginaPizza.o: tests/PizzaClass/ReginaPizza.cpp.o
.PHONY : tests/PizzaClass/ReginaPizza.o

# target to build an object file
tests/PizzaClass/ReginaPizza.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/ReginaPizza.cpp.o
.PHONY : tests/PizzaClass/ReginaPizza.cpp.o

tests/PizzaClass/ReginaPizza.i: tests/PizzaClass/ReginaPizza.cpp.i
.PHONY : tests/PizzaClass/ReginaPizza.i

# target to preprocess a source file
tests/PizzaClass/ReginaPizza.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/ReginaPizza.cpp.i
.PHONY : tests/PizzaClass/ReginaPizza.cpp.i

tests/PizzaClass/ReginaPizza.s: tests/PizzaClass/ReginaPizza.cpp.s
.PHONY : tests/PizzaClass/ReginaPizza.s

# target to generate assembly for a file
tests/PizzaClass/ReginaPizza.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/PizzaClass/ReginaPizza.cpp.s
.PHONY : tests/PizzaClass/ReginaPizza.cpp.s

tests/SafeQueueClass.o: tests/SafeQueueClass.cpp.o
.PHONY : tests/SafeQueueClass.o

# target to build an object file
tests/SafeQueueClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/SafeQueueClass.cpp.o
.PHONY : tests/SafeQueueClass.cpp.o

tests/SafeQueueClass.i: tests/SafeQueueClass.cpp.i
.PHONY : tests/SafeQueueClass.i

# target to preprocess a source file
tests/SafeQueueClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/SafeQueueClass.cpp.i
.PHONY : tests/SafeQueueClass.cpp.i

tests/SafeQueueClass.s: tests/SafeQueueClass.cpp.s
.PHONY : tests/SafeQueueClass.s

# target to generate assembly for a file
tests/SafeQueueClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/SafeQueueClass.cpp.s
.PHONY : tests/SafeQueueClass.cpp.s

tests/ThreadClass.o: tests/ThreadClass.cpp.o
.PHONY : tests/ThreadClass.o

# target to build an object file
tests/ThreadClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/ThreadClass.cpp.o
.PHONY : tests/ThreadClass.cpp.o

tests/ThreadClass.i: tests/ThreadClass.cpp.i
.PHONY : tests/ThreadClass.i

# target to preprocess a source file
tests/ThreadClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/ThreadClass.cpp.i
.PHONY : tests/ThreadClass.cpp.i

tests/ThreadClass.s: tests/ThreadClass.cpp.s
.PHONY : tests/ThreadClass.s

# target to generate assembly for a file
tests/ThreadClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests/ThreadClass.cpp.s
.PHONY : tests/ThreadClass.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fclean"
	@echo "... re"
	@echo "... tests_run"
	@echo "... plazza"
	@echo "... unit_tests"
	@echo "... src/Error/Error.o"
	@echo "... src/Error/Error.i"
	@echo "... src/Error/Error.s"
	@echo "... src/IConditionVariable/ConditionVariable.o"
	@echo "... src/IConditionVariable/ConditionVariable.i"
	@echo "... src/IConditionVariable/ConditionVariable.s"
	@echo "... src/IMutex/Mutex.o"
	@echo "... src/IMutex/Mutex.i"
	@echo "... src/IMutex/Mutex.s"
	@echo "... src/IMutex/ScopedLock/ScopedLock.o"
	@echo "... src/IMutex/ScopedLock/ScopedLock.i"
	@echo "... src/IMutex/ScopedLock/ScopedLock.s"
	@echo "... src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.o"
	@echo "... src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.i"
	@echo "... src/Plazza/Kitchen/Bodyguard/BodyguardRoutine.s"
	@echo "... src/Plazza/Kitchen/Cook/CookRoutine.o"
	@echo "... src/Plazza/Kitchen/Cook/CookRoutine.i"
	@echo "... src/Plazza/Kitchen/Cook/CookRoutine.s"
	@echo "... src/Plazza/Kitchen/Kitchen.o"
	@echo "... src/Plazza/Kitchen/Kitchen.i"
	@echo "... src/Plazza/Kitchen/Kitchen.s"
	@echo "... src/Plazza/Kitchen/Pantry/Pantry.o"
	@echo "... src/Plazza/Kitchen/Pantry/Pantry.i"
	@echo "... src/Plazza/Kitchen/Pantry/Pantry.s"
	@echo "... src/Plazza/Parser/Parser.o"
	@echo "... src/Plazza/Parser/Parser.i"
	@echo "... src/Plazza/Parser/Parser.s"
	@echo "... src/Plazza/Pizza/APizza.o"
	@echo "... src/Plazza/Pizza/APizza.i"
	@echo "... src/Plazza/Pizza/APizza.s"
	@echo "... src/Plazza/Pizza/Americana/AmericanaPizza.o"
	@echo "... src/Plazza/Pizza/Americana/AmericanaPizza.i"
	@echo "... src/Plazza/Pizza/Americana/AmericanaPizza.s"
	@echo "... src/Plazza/Pizza/Fantasia/FantasiaPizza.o"
	@echo "... src/Plazza/Pizza/Fantasia/FantasiaPizza.i"
	@echo "... src/Plazza/Pizza/Fantasia/FantasiaPizza.s"
	@echo "... src/Plazza/Pizza/Margarita/MargaritaPizza.o"
	@echo "... src/Plazza/Pizza/Margarita/MargaritaPizza.i"
	@echo "... src/Plazza/Pizza/Margarita/MargaritaPizza.s"
	@echo "... src/Plazza/Pizza/Regina/ReginaPizza.o"
	@echo "... src/Plazza/Pizza/Regina/ReginaPizza.i"
	@echo "... src/Plazza/Pizza/Regina/ReginaPizza.s"
	@echo "... src/Plazza/Reception/Reception.o"
	@echo "... src/Plazza/Reception/Reception.i"
	@echo "... src/Plazza/Reception/Reception.s"
	@echo "... src/Timer/Timer.o"
	@echo "... src/Timer/Timer.i"
	@echo "... src/Timer/Timer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/KitchenClass/Kitchen.o"
	@echo "... tests/KitchenClass/Kitchen.i"
	@echo "... tests/KitchenClass/Kitchen.s"
	@echo "... tests/KitchenClass/PantryClass/Pantry.o"
	@echo "... tests/KitchenClass/PantryClass/Pantry.i"
	@echo "... tests/KitchenClass/PantryClass/Pantry.s"
	@echo "... tests/ParserClass.o"
	@echo "... tests/ParserClass.i"
	@echo "... tests/ParserClass.s"
	@echo "... tests/PizzaClass/AmericanaPizza.o"
	@echo "... tests/PizzaClass/AmericanaPizza.i"
	@echo "... tests/PizzaClass/AmericanaPizza.s"
	@echo "... tests/PizzaClass/FantasiaPizza.o"
	@echo "... tests/PizzaClass/FantasiaPizza.i"
	@echo "... tests/PizzaClass/FantasiaPizza.s"
	@echo "... tests/PizzaClass/MargaritaPizza.o"
	@echo "... tests/PizzaClass/MargaritaPizza.i"
	@echo "... tests/PizzaClass/MargaritaPizza.s"
	@echo "... tests/PizzaClass/ReginaPizza.o"
	@echo "... tests/PizzaClass/ReginaPizza.i"
	@echo "... tests/PizzaClass/ReginaPizza.s"
	@echo "... tests/SafeQueueClass.o"
	@echo "... tests/SafeQueueClass.i"
	@echo "... tests/SafeQueueClass.s"
	@echo "... tests/ThreadClass.o"
	@echo "... tests/ThreadClass.i"
	@echo "... tests/ThreadClass.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

